### PR TITLE
Minor updates on readme

### PR DESCRIPTION
**Pull request by jackalcooper**

### CODE REVIEW

**Comment by cocoa-xu** [comment]
`dlopen` and `dlsym` are **declared** in `Ctypes` as well. `Ctypes.dlopen` and `Ctypes.dlsym` are different from the ones in module `Otter`.

**Comment by cocoa-xu** [comment]
`Otter.dl*` calls go to NIFs `otter_dl*` while `Ctypes.dl*` calls going to `Otter.invoke` which redirects to the `otter_invoke` NIF.

**Comment by jackalcooper** [comment]
> `dlopen` and `dlsym` are **declared** in `Ctypes` as well. `Ctypes.dlopen` and `Ctypes.dlsym` are different from the ones in module `Otter`.

Then I guess the declaration is broke. I got
```
function MLIR.CAPI.IR.dlopen/2 is undefined or private
```

**Comment by cocoa-xu** [comment]
The declaration is in the `ctypes_demo.ex` file, and if you'd like to use the `invoke` version, then they should be declared in your module as well. Just like how you `extern` them in a header file.

```elixir
  extern dlopen(:c_ptr, c_ptr, s32)
  extern dlsym(:c_ptr, c_ptr, c_ptr)
```

If you'd like to use the NIF version of them, then you need to call `Otter.dl*` functions.

`Ctype.dlopen` is obtained by `Otter.dlopen` and `Otter.dlsym`. Just like the `sin` and `cos` functions in `Ctypes`, `dlopen` and `dlsym` are functions that can be dlsym'ed as well.

**Comment by jackalcooper** [comment]
Now I get it, thanks for the explanation.

**Comment by cocoa-xu** [comment]
No worries! I'll add these notes in the readme file.

**Pull request closed without merging**
